const quotes = [
    {quote: 'Do falset take life too seriously. You will never get out of it alive.', 
     source: 'Elbert Hubbard', 
     citation: 'quotesgram.com', 
     category: 'humor', 
     grannyApproval: false},
    {quote: 'Always remember that you are absolutely unique. Just like everyone else.', 
     source: 'Margaret Mead', 
     citation: 'quotesgram.com', 
     category: 'humor', 
     grannyApproval: true},
    {quote: 'I\'m sorry, if you were right, I\'d agree with you.', 
     source: 'Robin Williams', 
     citation: 'quotesgram.com', 
     category: 'humor', 
     grannyApproval: false},
    {quote: 'Progress is man\'s ability to complicate simplicity.', 
     source: 'Thor Heyerdahl', 
     citation: 'quotesgram.com', 
     category: 'history', 
     grannyApproval: false},
    {quote: 'The best thing about a boolean is even if you are wrong, you are only off by a bit.', 
     source: 'Anonymous', 
     citation: 'jounaldev.com', 
     category: 'computer science', 
     grannyApproval: false},
    {quote: 'Without requirements or design, programming is the art of adding bugs to an empty text file.', 
     source: 'Louis Srygley', 
     citation: 'jounaldev.com', 
     category: 'computer science', 
     grannyApproval: false},
    {quote: 'Before software can be reusable it first has to be usable.', 
     source: 'Ralph Johnson', 
     citation: 'jounaldev.com', 
     category: 'computer science', 
     grannyApproval: false},
    {quote: 'The best method for accelerating a computer is the one that boosts it by 9.8 m/s^2', 
     source: 'Anonymous', 
     citation: 'jounaldev.com', 
     category: 'humor', 
     grannyApproval: true},
    {quote: 'If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization.', 
     source: 'Gerald Weinberg', 
     citation: 'jounaldev.com', 
     category: 'computer science', 
     grannyApproval: false},
    {quote: 'There are two ways to write error-free programs; only the third one works.', 
     source: 'Alan J. Perlis', 
     citation: 'jounaldev.com', 
     category: 'humor', 
     grannyApproval: false},
    {quote: 'Ready, fire, aim: the fast approach to software development. Ready, aim, aim, aim, aim: the slow approach to software development.', 
     source: 'Annonymous', 
     citation: 'jounaldev.com', 
     category: 'computer science',
     year: 2014, 
     grannyApproval: false},
    {quote: 'One man’s crappy software is another man’s full-time job.', 
     source: 'Jessica Gaston', 
     citation: 'jounaldev.com', 
     category: 'humor', 
     grannyApproval: false},
    {quote: 'A good programmer is someone who always looks both ways before crossing a one-way street.', 
     source: 'Doug Linder', 
     citation: 'jounaldev.com', 
     category: 'humor', 
     grannyApproval: false},
    {quote: 'Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.', 
     source: 'Martin Golding', 
     citation: 'jounaldev.com', 
     category: 'humor', 
     grannyApproval: false},
    {quote: 'Deleted code is debugged code.', 
     source: 'Jeff Sickel', 
     citation: 'jounaldev.com', 
     category: 'humor', 
     grannyApproval: false},
    {quote: 'Walking on water and developing software from a specification are easy if both are frozen.', 
     source: 'Edward V Berard', 
     citation: 'jounaldev.com', 
     category: 'computer science', 
     grannyApproval: true},
    {quote: 'If debugging is the process of removing software bugs, then programming must be the process of putting them in.', 
     source: 'Edsger Dijkstra', 
     citation: 'jounaldev.com', 
     category: 'computer science', 
     grannyApproval: false},
    {quote: 'Software undergoes beta testing shortly before it’s released. Beta is Latin for “still doesn’t work.', 
     source: 'Annonymous', 
     citation: 'jounaldev.com', 
     category: 'computer science', 
     year: 2008,
     grannyApproval: false},
    {quote: 'Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to produce bigger and better idiots. So far, the universe is winning.', 
     source: 'Rick Cook', 
     citation: 'jounaldev.com', 
     category: 'humor', 
     grannyApproval: true},
    {quote: 'The best performance improvement is the transition from the nonworking state to the working state.', 
     source: 'J. Osterhout', 
     citation: 'jounaldev.com', 
     category: 'computer science', 
     grannyApproval: true},
    {quote: 'In order to understand recursion, one must first understand recursion.', 
     source: 'Annonymous', 
     citation: 'jounaldev.com', 
     category: 'computer science',
     year: 1998, 
     grannyApproval: false},
    {quote: 'Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.', 
     source: 'Mosher\'s Law of Software Engineering', 
     citation: 'jounaldev.com', 
     category: 'humor', 
     grannyApproval: false},
    {quote: 'Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program.', 
     source: 'Linus Torvalds', 
     citation: 'junauza.com', 
     category: 'computer science', 
     grannyApproval: false},
    {quote: 'Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.', 
     source: 'Brian W. Kernighan', 
     citation: 'junauza.com', 
     category: 'humor', 
     grannyApproval: false},
    {quote: 'Measuring programming progress by lines of code is like measuring aircraft building progress by weight.', 
     source: 'Bill Gates', 
     citation: 'junauza.com', 
     category: 'computer science', 
     grannyApproval: false},
    {quote: 'Computer system analysis is like child-rearing; you can do grievous damage, but you cannot ensure success.', 
     source: 'Tom DeMarco', 
     citation: 'junauza.com', 
     category: 'humor', 
     grannyApproval: false},
    {quote: 'Beware of bugs in the above code; I have only proved it correct, not tried it.', 
     source: 'Donald E. Knuth', 
     citation: 'junauza.com', 
     category: 'computer science', 
     grannyApproval: false},
    {quote: 'In theory, theory and practice are the same. In practice, they’re not.', 
     source: 'Yoggi Berra', 
     citation: 'junauza.com', 
     category: 'engineering', 
     grannyApproval: true},
    {quote: 'Perfection [in design] is achieved, not when there is nothing more to add, but when there is nothing left to take away.', 
     source: 'Antoine de Saint-Exupéry', 
     citation: 'junauza.com', 
     category: 'computer science', 
     grannyApproval: true},
    {quote: 'Talk is cheap. Show me the code.', 
     source: 'Linus Torvalds', 
     citation: 'junauza.com', 
     grannyApproval: false},
    {quote: 'Python\'s a drop-in replacement for BASIC in the sense that Optimus Prime is a drop-in replacement for a truck.', 
     source: 'Cory Dodt', 
     citation: 'junauza.com',
     grannyApproval: false},
    {quote: 'Good design adds value faster than it adds cost.', 
     source: 'Thomas C. Gale', 
     citation: 'junauza.com', 
     grannyApproval: true},
    {quote: 'When someone says: "I want a programming language in which I need only say what I wish done", give him a lollipop.', 
     source: 'Alan J. Perlis', 
     citation: 'junauza.com', 
     grannyApproval: false},
    {quote: 'FORTRAN is not a flower but a weed — it is hardy, occasionally blooms, and grows in every computer.', 
     source: 'Alan J. Perlis', 
     citation: 'junauza.com',
     grannyApproval: false},
    {quote: 'In the one and only true way. The object-oriented version of \'Spaghetti code\' is, of course, \'Lasagna code\'. (Too many layers).', 
     source: 'Roberto Waltman', 
     citation: 'junauza.com', 
     grannyApproval: false},
    {quote: 'Computer science education cannot make anybody an expert programmer any more than studying brushes and pigment can make somebody an expert painter.', 
     source: 'Eric S. Raymond', 
     citation: 'junauza.com', 
     grannyApproval: false},
    {quote: 'I have always wished for my computer to be as easy to use as my telephone; my wish has come true because I can no longer figure out how to use my telephone.', 
     source: 'Bjarne Stroustrup', 
     citation: 'junauza.com', 
     grannyApproval: true}
  ]