const quotes = [
    {quote: 'Do not take life too seriously. You will never get out of it alive.', 
     source: 'Elbert Hubbard', 
     citation: 'https://quotesgram.com/funny-programming-quotes/'},
    {quote: 'Always remember that you are absolutely unique. Just like everyone else.', 
     source: 'Margaret Mead', 
     citation: 'https://quotesgram.com/funny-programming-quotes/'},
    {quote: 'I'm sorry, if you were right, I'd agree with you.', 
     source: 'Robin Williams', 
     citation: 'https://quotesgram.com/funny-programming-quotes/'},
    {quote: 'Progress is man's ability to complicate simplicity.', 
     source: 'Thor Heyerdahl', 
     citation: 'https://quotesgram.com/funny-programming-quotes/'},
    {quote: 'The best thing about a boolean is even if you are wrong, you are only off by a bit.', 
     source: 'Anonymous', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'Without requirements or design, programming is the art of adding bugs to an empty text file.', 
     source: 'Louis Srygley', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'Before software can be reusable it first has to be usable.', 
     source: 'Ralph Johnson', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'The best method for accelerating a computer is the one that boosts it by 9.8 m/s^2', 
     source: 'Anonymous', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization.', 
     source: 'Gerald Weinberg', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'There are two ways to write error-free programs; only the third one works.', 
     source: 'Alan J. Perlis', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'Ready, fire, aim: the fast approach to software development. Ready, aim, aim, aim, aim: the slow approach to software development.', 
     source: 'Annonymous', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'One man’s crappy software is another man’s full-time job.', 
     source: 'Jessica Gaston', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'A good programmer is someone who always looks both ways before crossing a one-way street.', 
     source: 'Doug Linder', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.', 
     source: 'Martin Golding', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'Deleted code is debugged code.', 
     source: 'Jeff Sickel', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'Walking on water and developing software from a specification are easy if both are frozen.', 
     source: 'Edward V Berard', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'If debugging is the process of removing software bugs, then programming must be the process of putting them in.', 
     source: 'Edsger Dijkstra', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'Software undergoes beta testing shortly before it’s released. Beta is Latin for “still doesn’t work.', 
     source: 'Annonymous', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to produce bigger and better idiots. So far, the universe is winning.', 
     source: 'Rick Cook', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'The best performance improvement is the transition from the nonworking state to the working state.', 
     source: 'J. Osterhout', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'In order to understand recursion, one must first understand recursion.', 
     source: 'Annonymous', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.', 
     source: 'Mosher\'s Law of Software Engineering', 
     citation: 'https://www.journaldev.com/240/my-25-favorite-programming-quotes-that-are-funny-too'},
    {quote: 'There are two ways of constructing a software design. One way is to make it so simple that there are obviously no deficiencies. And the other way is to make it so complicated that there are no obvious deficiencies.', 
     source: 'C.A.R. Hoare', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program.', 
     source: 'Linus Torvalds', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'On two occasions I have been asked [by members of Parliament]: \'Pray, Mr. Babbage, if you put into the machine wrong figures, will the right answers come out?\' I am not able rightly to apprehend the kind of confusion of ideas that could provoke such a question.', 
     source: 'Charles Babbage', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'Most software today is very much like an Egyptian pyramid with millions of bricks piled on top of each other, with no structural integrity, but just done by brute force and thousands of slaves.', 
     source: 'Alan Kay', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'People think that computer science is the art of geniuses but the actual reality is the opposite, just many people doing things that build on each other, like a wall of mini stones.', 
     source: 'Donald Knuth', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.', 
     source: 'Brian W. Kernighan', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'Measuring programming progress by lines of code is like measuring aircraft building progress by weight.', 
     source: 'Bill Gates', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'Computer system analysis is like child-rearing; you can do grievous damage, but you cannot ensure success.', 
     source: 'Tom DeMarco', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'Beware of bugs in the above code; I have only proved it correct, not tried it.', 
     source: 'Donald E. Knuth', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'If McDonalds were run like a software company, one out of every hundred Big Macs would give you food poisoning, and the response would be, "We’re sorry, here’s a coupon for two more." ', 
     source: 'Mark Minasi', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'In theory, theory and practice are the same. In practice, they’re not.', 
     source: 'Yoggi Berra', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'Perfection [in design] is achieved, not when there is nothing more to add, but when there is nothing left to take away.', 
     source: 'Antoine de Saint-Exupéry', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'Talk is cheap. Show me the code.', 
     source: 'Linus Torvalds', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'Python's a drop-in replacement for BASIC in the sense that Optimus Prime is a drop-in replacement for a truck.', 
     source: 'Cory Dodt', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'Good design adds value faster than it adds cost.', 
     source: 'Thomas C. Gale', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'When someone says: "I want a programming language in which I need only say what I wish done", give him a lollipop.', 
     source: 'Alan J. Perlis', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'FORTRAN is not a flower but a weed — it is hardy, occasionally blooms, and grows in every computer.', 
     source: 'Alan J. Perlis', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'In the one and only true way. The object-oriented version of 'Spaghetti code' is, of course, 'Lasagna code'. (Too many layers).', 
     source: 'Roberto Waltman', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'Computer science education cannot make anybody an expert programmer any more than studying brushes and pigment can make somebody an expert painter.', 
     source: 'Eric S. Raymond', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'},
    {quote: 'I have always wished for my computer to be as easy to use as my telephone; my wish has come true because I can no longer figure out how to use my telephone.', 
     source: 'Bjarne Stroustrup', 
     citation: 'https://www.junauza.com/2010/12/top-50-programming-quotes-of-all-time.html'}
  ]