//generates a random integer from 1 up to the input
function getRandomNumber(max) {
  let randomN;
  randomN = Math.floor(Math.random()*max) + 1;
  return randomN;
}

//returns a random quote object from the quotes array
function getRandomQuote() {
  let index = getRandomNumber(quotes.length) - 1;
  return quotes[index];
}

function buildHtmlStr(randomQuote, strHTML) {
  strHTML += '<p class="quote">' + randomQuote.quote + '</p>';
  strHTML += '<p class="source">' + randomQuote.source;
  if (randomQuote.citation !== '') {
    strHTML += '<span class="citation">' + randomQuote.citation + '</span>';
  }
  if (randomQuote.hasOwnProperty('year')){
    strHTML += '<span class="year">' + randomQuote.year + '</span>';
  }
  strHTML += '</p>';
  if (randomQuote.hasOwnProperty('category')){
    strHTML += '<p class="category">category: ' + randomQuote.category;
  } else {
    strHTML += '<p class="category">';
  }
  if (randomQuote.hasOwnProperty('grannyApproval')) {
      if (randomQuote.grannyApproval) {
      strHTML += ' | My grandma approves this message'
    } else {
      strHTML += ' | My grandma does not approve this message'
    }
  }
  strHTML += '</p>';
  return strHTML;
}

function randomBgColor() {
  let randomColor = 'body {background-color: rgb(';
  randomColor += (getRandomNumber(256) - 1) + ', ' + (getRandomNumber(256) - 1) + ', ' + (getRandomNumber(256) - 1);
  randomColor += ')}'
  let bgColor = document.getElementById('bgColor');
  bgColor.innerHTML = randomColor;
}

/***
 * constructs an html string from properties of an 
 * quote object generated by getRandomQuote().
 * 
 * Each propery of the quote is each labeled as 
 * a different class. Source, citation, and year 
 * property are on the same paragraph.
 * 
 * The string is then passed to the div tag with
 * ID 'quote-box' in index.html
 */
function printQuote() {
  let randomQuote = getRandomQuote();
  let strHTML = '';
  strHTML = buildHtmlStr(randomQuote, strHTML);
  let quoteBoxDiv = document.getElementById('quote-box');
  quoteBoxDiv.innerHTML = strHTML;
  randomBgColor();
}

printQuote();
interv = setInterval(printQuote, 20000);

/***
  Clicking the button calls printQuote();
***/

document.getElementById('loadQuote').addEventListener("click", printQuote, false);