//generates a random integer from 1 up to the input
function getRandomNumber(max) {
  let randomN;
  randomN = Math.floor(Math.random()*max) + 1;
  return randomN;
}

//returns a random quote object from the quotes array
function getRandomQuote() {
  let index = getRandomNumber(quotes.length) - 1;
  return quotes[index];
}

/***
 * cosntructs and returns an html string according to 
 * the properties of the quote object passed to it
 */
function buildHtmlStr(randomQuote) {
  let strHTML = '';
  strHTML += '<p class="quote">' + randomQuote.quote + '</p>';
  strHTML += '<p class="source">' + randomQuote.source;
  if (randomQuote.citation !== '') {
    strHTML += '<span class="citation">' + randomQuote.citation + '</span>';
  }
  if (randomQuote.hasOwnProperty('year')){
    strHTML += '<span class="year">' + randomQuote.year + '</span>';
  }
  strHTML += '</p>';
  if (randomQuote.hasOwnProperty('category')){
    strHTML += '<p class="category">category: ' + randomQuote.category;
  } else {
    strHTML += '<p class="category">';
  }
  if (randomQuote.hasOwnProperty('grannyApproval')) {
      if (randomQuote.grannyApproval) {
      strHTML += ' | My grandma approves this message'
    } else {
      strHTML += ' | My grandma does not approve this message'
    }
  }
  strHTML += '</p>';
  return strHTML;
}

/***
 * generates a random background color for the body
 * of index.html
 */
function randomBgColor() {
  let randomColor = 'body {background-color: rgb(';
  randomColor += (getRandomNumber(256) - 1) + ',' + (getRandomNumber(256) - 1) + ',' + (getRandomNumber(256) - 1);
  randomColor += ')}'
  let bgColor = document.getElementById('bgColor');
  bgColor.innerHTML = randomColor;
}

/***
 * Prints the quote string generated by getRandomQuote()
 * to the quote-box and changes the background color
 */
function printQuote() {
  let randomQuote = getRandomQuote();
  let strHTML;
  strHTML = buildHtmlStr(randomQuote);
  let quoteBoxDiv = document.getElementById('quote-box');
  quoteBoxDiv.innerHTML = strHTML;
  randomBgColor();
}

printQuote();

//changes the quote every 20 seconds
interv = setInterval(printQuote, 20000);

/***
  Clicking the button calls printQuote();
***/
document.getElementById('loadQuote').addEventListener("click", printQuote, false);